# .github/workflows/publish-to-pypi.yml
name: Publish Python Package

on:
  push:
    tags:
      - "v*" # Triggers the workflow when a new tag starting with 'v' is pushed (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__ # PyPI uses __token__ as a placeholder for the username
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*
